name: 'IMDb Export'
description: 'A GitHub action that allows you to export your IMDb ratings and watchlist as csv to repository'
inputs:
  imdb_email:
    description: 'myokhant155@gmail.com'
    required: true
  imdb_password:
    description: 'nnDA3vaAmiJv7i$'
    required: true
  GITHUB_TOKEN:
    description: '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'
    required: true
  ratings_path:
    description: 'Ratings file path in repository'
    required: false
    default: 'imdb_ratings.csv'
  ratings_commit_message:
    description: 'Commit message when updating ratings file'
    required: false
    default: 'Update IMDb Ratings'
  watchlist_path:
    description: 'Watchlist file path in repository'
    required: false
    default: 'imdb_watchlist.csv'
  watchlist_commit_message:
    description: 'Commit message when updating watchlist file'
    required: false
    default: 'Update IMDb Watchlist'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'download'
  color: 'yellow'
